In [1]:
import pandas as pd
import sqlite3

## Подробная инструкция:
1. Положи файл базы данных в подпапку data внутри каталога src.
2. Создай соединение с базой данных с помощью библиотеки sqlite3.
3. Получи схему таблицы pageviews, используя pd.io.sql.read_sql() и запрос: "PRAGMA table_info(pageviews);"
4. Получи только первые десять строк таблицы pageviews, чтобы ознакомиться с её структурой.
5. Одним запросом получи подтаблицу, удовлетворяющую следующим условиям:
    - используются только столбцы "uid" и "datetime";
    - выбираются только пользовательские данные (user_*), данные администраторов исключаются;
    - данные отсортированы по "uid" в порядке возрастания;
    - столбец "datetime" используется в качестве индекса;
    - столбец "datetime" преобразован в тип DatetimeIndex;
    - имя результирующего DataFrame - pageviews.
6. Закрой соединение с базой данных.

In [2]:
db_path = '../data/checking-logs.sqlite'
conn = sqlite3.connect(db_path)

In [3]:
schema = pd.io.sql.read_sql('PRAGMA table_info(pageviews);', conn)
print('===Схема таблицы pageviews===')
schema

===Схема таблицы pageviews===

   cid      name       type  notnull dflt_value  pk
0    0     index    INTEGER        0       None   0
1    1       uid       TEXT        0       None   0
2    2  datetime  TIMESTAMP        0       None   0

In [4]:
first_ten_obj = pd.io.sql.read_sql('SELECT * FROM pageviews LIMIT 10;', conn)
print('===Первые 10 объектов===')
first_ten_obj

===Первые 10 объектов===

   index      uid                    datetime
0      0  admin_1  2020-04-17 12:01:08.463179
1      1  admin_1  2020-04-17 12:01:23.743946
2      2  admin_3  2020-04-17 12:17:39.287778
3      3  admin_3  2020-04-17 12:17:40.001768
4      4  admin_1  2020-04-17 12:27:30.646665
5      5  admin_1  2020-04-17 12:35:44.884757
6      6  admin_1  2020-04-17 12:35:52.735016
7      7  admin_3  2020-04-17 12:36:21.401412
8      8  admin_3  2020-04-17 12:36:22.023355
9      9  admin_1  2020-04-17 13:55:19.129243

In [5]:
pageviews = pd.io.sql.read_sql(
    """
    SELECT uid, datetime
    FROM pageviews
    WHERE uid LIKE 'user_%'
    ORDER BY uid;
    """,
    conn,
    index_col = 'datetime',
    parse_dates = ['datetime']
)

print('===Датафрейм pageviews===')
pageviews

===Датафрейм pageviews===

                                uid
datetime
2020-04-26 21:53:59.624136   user_1
2020-04-26 22:06:19.478143   user_1
2020-04-26 22:12:09.614497   user_1
2020-04-30 19:29:01.831635   user_1
2020-05-05 20:26:32.894852   user_1
...                             ...
2020-04-29 16:51:21.877630  user_30
2020-05-09 20:30:47.034282  user_30
2020-05-22 11:30:18.368990   user_5
2020-05-21 16:28:28.217529   user_9
2020-05-21 16:36:40.915488   user_9

[987 rows x 1 columns]

In [6]:
print(f'Тип индекса: {type(pageviews.index)}')

Тип индекса: <class 'pandas.DatetimeIndex'>

In [7]:
conn.close()

In [8]:
pageviews.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 987 entries, 2020-04-26 21:53:59.624136 to 2020-05-21 16:36:40.915488
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uid     987 non-null    str
dtypes: str(1)
memory usage: 15.4 KB