# Day 09. Exercise 01
# Gridsearch

## 0. Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import itertools
from tqdm.notebook import tqdm
from sklearn.metrics import accuracy_score
import warnings

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
warnings.filterwarnings('ignore')

## 1. Preprocessing

1. Read the file [`day-of-week-not-scaled.csv`](https://drive.google.com/file/d/1AlGvsJDSzPT_70caausx8bFuupIEZkfh/view?usp=sharing). It is similar to the one from the previous exercise, but this time we did not scale continuous features (we are not going to use logreg anymore). Don't forget to enrich the table with the 'dayofweek' column from the previous day's .csv-file.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [3]:
df = pd.read_csv('../data/day-of-week-not-scaled.csv')
df.head(1)

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,uid_user_16,uid_user_17,uid_user_18,uid_user_19,uid_user_2,uid_user_20,uid_user_21,uid_user_22,uid_user_23,uid_user_24,uid_user_25,uid_user_26,uid_user_27,uid_user_28,uid_user_29,uid_user_3,uid_user_30,uid_user_31,uid_user_4,uid_user_6,uid_user_7,uid_user_8,labname_code_rvw,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1686 entries, 0 to 1685
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   numTrials         1686 non-null   int64
 1   hour              1686 non-null   int64
 2   uid_user_0        1686 non-null   float64
 3   uid_user_1        1686 non-null   float64
 4   uid_user_10       1686 non-null   float64
 5   uid_user_11       1686 non-null   float64
 6   uid_user_12       1686 non-null   float64
 7   uid_user_13       1686 non-null   float64
 8   uid_user_14       1686 non-null   float64
 9   uid_user_15       1686 non-null   float64
 10  uid_user_16       1686 non-null   float64
 11  uid_user_17       1686 non-null   float64
 12  uid_user_18       1686 non-null   float64
 13  uid_user_19       1686 non-null   float64
 14  uid_user_2        1686 non-null   float64
 15  uid_user_20       1686 non-null   float64
 16  uid_user_21       1686 non-null   float64
 17  uid_user_22       1686 non-null   float64
 18  uid_user_23       1686 non-null   float64
 19  uid_user_24       1686 non-null   float64
 20  uid_user_25       1686 non-null   float64
 21  uid_user_26       1686 non-null   float64
 22  uid_user_27       1686 non-null   float64
 23  uid_user_28       1686 non-null   float64
 24  uid_user_29       1686 non-null   float64
 25  uid_user_3        1686 non-null   float64
 26  uid_user_30       1686 non-null   float64
 27  uid_user_31       1686 non-null   float64
 28  uid_user_4        1686 non-null   float64
 29  uid_user_6        1686 non-null   float64
 30  uid_user_7        1686 non-null   float64
 31  uid_user_8        1686 non-null   float64
 32  labname_code_rvw  1686 non-null   float64
 33  labname_lab02     1686 non-null   float64
 34  labname_lab03     1686 non-null   float64
 35  labname_lab03s    1686 non-null   float64
 36  labname_lab05s    1686 non-null   float64
 37  labname_laba04    1686 non-null   float64
 38  labname_laba04s   1686 non-null   float64
 39  labname_laba05    1686 non-null   float64
 40  labname_laba06    1686 non-null   float64
 41  labname_laba06s   1686 non-null   float64
 42  labname_project1  1686 non-null   float64
dtypes: float64(41), int64(2)
memory usage: 566.5 KB

In [5]:
day_of_week = pd.read_csv('../data/dayofweek.csv', usecols=['dayofweek'])
day_of_week.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1686 entries, 0 to 1685
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   dayofweek  1686 non-null   int64
dtypes: int64(1)
memory usage: 13.3 KB

In [6]:
df = pd.concat([day_of_week, df], axis=1)
df.head(1)

,dayofweek,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,uid_user_16,uid_user_17,uid_user_18,uid_user_19,uid_user_2,uid_user_20,uid_user_21,uid_user_22,uid_user_23,uid_user_24,uid_user_25,uid_user_26,uid_user_27,uid_user_28,uid_user_29,uid_user_3,uid_user_30,uid_user_31,uid_user_4,uid_user_6,uid_user_7,uid_user_8,labname_code_rvw,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,4,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
RANDOM_STATE=21
X = df.drop(columns=['dayofweek'])
y = df['dayofweek']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y)

## 2. SVM gridsearch

1. Using `GridSearchCV` try different parameters of kernel (`linear`, `rbf`, `sigmoid`), C (`0.01`, `0.1`, `1`, `1.5`, `5`, `10`), gamma (`scale`, `auto`), class_weight (`balanced`, `None`) use `random_state=21` and `probability=True` and get the best combination of them in terms of accuracy.
2. Create a dataframe from the results of the gridsearch and sort it ascendingly by the `rank_test_score`. Check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [8]:
params_svc = {
    'kernel': ['linear', 'rbf', 'sigmoid'],
    'C': [0.01, 0.1, 1, 1.5, 5, 10],
    'gamma': ['scale', 'auto'],
    'class_weight': ['balanced', None]
}

svc = SVC(random_state=RANDOM_STATE, probability=True)

grid_search_svc = GridSearchCV(
    svc,
    params_svc,
    scoring='accuracy',
    n_jobs=-1
)

grid_search_svc.fit(X_train, y_train)

GridSearchCV(estimator=SVC(probability=True, random_state=21), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 1.5, 5, 10],
                         'class_weight': ['balanced', None],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'sigmoid']},
             scoring='accuracy')

In [9]:
print(f'Лучшие параметры: {grid_search_svc.best_params_}')
print(f'Accuracy на кросс-валидации: {grid_search_svc.best_score_}')

Лучшие параметры: {'C': 10, 'class_weight': None, 'gamma': 'auto', 'kernel': 'rbf'}
Accuracy на кросс-валидации: 0.8761090458488228

In [10]:
results_svc = pd.DataFrame(grid_search_svc.cv_results_)
cols = ['param_kernel', 'param_C', 'param_gamma', 'param_class_weight', 'mean_test_score', 'std_test_score', 'rank_test_score']
results_svc = results_svc[cols].sort_values('rank_test_score')
results_svc

,param_kernel,param_C,param_gamma,param_class_weight,mean_test_score,std_test_score,rank_test_score
70,rbf,10,auto,None,0.876109,0.018419,1
64,rbf,10,auto,balanced,0.863500,0.010870,2
58,rbf,5,auto,None,0.816018,0.008116,3
52,rbf,5,auto,balanced,0.808608,0.021007,4
63,linear,10,auto,balanced,0.721052,0.034438,5
60,linear,10,scale,balanced,0.721052,0.034438,5
66,linear,10,scale,None,0.719587,0.017463,7
69,linear,10,auto,None,0.719587,0.017463,7
51,linear,5,auto,balanced,0.706234,0.031619,9
48,linear,5,scale,balanced,0.706234,0.031619,9
57,linear,5,auto,None,0.691411,0.025798,11
54,linear,5,scale,None,0.691411,0.025798,11
36,linear,1.5,scale,balanced,0.665419,0.016680,13
39,linear,1.5,auto,balanced,0.665419,0.016680,13
45,linear,1.5,auto,None,0.662481,0.022371,15
42,linear,1.5,scale,None,0.662481,0.022371,15
30,linear,1,scale,None,0.657277,0.019903,17
33,linear,1,auto,None,0.657277,0.019903,17
27,linear,1,auto,balanced,0.638720,0.021487,19
24,linear,1,scale,balanced,0.638720,0.021487,19
40,rbf,1.5,auto,balanced,0.627603,0.024032,21
46,rbf,1.5,auto,None,0.620187,0.015624,22
18,linear,0.1,scale,None,0.564549,0.009398,23
21,linear,0.1,auto,None,0.564549,0.009398,23
34,rbf,1,auto,None,0.563059,0.027559,25
28,rbf,1,auto,balanced,0.529652,0.029831,26
15,linear,0.1,auto,balanced,0.519262,0.047914,27
12,linear,0.1,scale,balanced,0.519262,0.047914,27
67,rbf,10,scale,None,0.410222,0.017767,29
61,rbf,10,scale,balanced,0.394639,0.012779,30
55,rbf,5,scale,None,0.366446,0.021040,31
22,rbf,0.1,auto,None,0.360501,0.021781,32
9,linear,0.01,auto,None,0.357566,0.013138,33
6,linear,0.01,scale,None,0.357566,0.013138,33
16,rbf,0.1,auto,balanced,0.349415,0.006795,35
0,linear,0.01,scale,balanced,0.339771,0.007641,36
3,linear,0.01,auto,balanced,0.339771,0.007641,36
43,rbf,1.5,scale,None,0.336784,0.019890,38
31,rbf,1,scale,None,0.325653,0.021187,39
49,rbf,5,scale,balanced,0.325645,0.014963,40
19,rbf,0.1,scale,None,0.310073,0.020703,41
37,rbf,1.5,scale,balanced,0.296726,0.015374,42
25,rbf,1,scale,balanced,0.286364,0.032595,43
20,sigmoid,0.1,scale,None,0.272240,0.015390,44
13,rbf,0.1,scale,balanced,0.241895,0.034040,45
68,sigmoid,10,scale,None,0.235134,0.020343,46
11,sigmoid,0.01,auto,None,0.234424,0.001779,47
10,rbf,0.01,auto,None,0.234424,0.001779,47
8,sigmoid,0.01,scale,None,0.234424,0.001779,47
7,rbf,0.01,scale,None,0.234424,0.001779,47
56,sigmoid,5,scale,None,0.234416,0.009336,51
23,sigmoid,0.1,auto,None,0.232942,0.003113,52
32,sigmoid,1,scale,None,0.230712,0.011807,53
44,sigmoid,1.5,scale,None,0.230712,0.011807,53
38,sigmoid,1.5,scale,balanced,0.218857,0.022662,55
62,sigmoid,10,scale,balanced,0.206926,0.029962,56
50,sigmoid,5,scale,balanced,0.204712,0.027158,57
35,sigmoid,1,auto,None,0.199609,0.043698,58
5,sigmoid,0.01,auto,balanced,0.199480,0.070023,59
4,rbf,0.01,auto,balanced,0.199480,0.070023,59
2,sigmoid,0.01,scale,balanced,0.199480,0.070023,59
1,rbf,0.01,scale,balanced,0.199480,0.070023,59
26,sigmoid,1,scale,balanced,0.189872,0.024804,63
14,sigmoid,0.1,scale,balanced,0.173584,0.017392,64
47,sigmoid,1.5,auto,None,0.166895,0.035449,65
59,sigmoid,5,auto,None,0.152796,0.038863,66
71,sigmoid,10,auto,None,0.132039,0.018485,67
53,sigmoid,5,auto,balanced,0.129792,0.019869,68
65,sigmoid,10,auto,balanced,0.115693,0.020052,69
41,sigmoid,1.5,auto,balanced,0.079380,0.006913,70
17,sigmoid,0.1,auto,balanced,0.062310,0.002678,71
29,sigmoid,1,auto,balanced,0.060088,0.009188,72

**Выводы**: разница между топ-1 и топ-2 моделью составляет всего 1%, причём топ-1 забрала модель без дополнительного баланса весов. Однако с топ-5, который занял kernel=linear, разрыв уже 15%, что существенно. Хуже всего показала себя сигмоида: большая часть моделей с данным кернелом - это случайное угадывание

## 3. Decision tree

1. Using `GridSearchCV` try different parameters of `max_depth` (from `1` to `49`), `class_weight` (`balanced`, `None`) and `criterion` (`entropy` and `gini`) and get the best combination of them in terms of accuracy. Use `random_state=21`.
2. Create a dataframe from the results of the gridsearch and sort it ascendingly by the `rank_test_score`, check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [11]:
params_tree = {
    'max_depth': range(1, 50),
    'class_weight': ['balanced', None],
    'criterion': ['entropy', 'gini']
}

tree = DecisionTreeClassifier(random_state=RANDOM_STATE)

grid_search_tree = GridSearchCV(
    tree,
    params_tree,
    scoring='accuracy',
    n_jobs=-1
)

grid_search_tree.fit(X_train, y_train)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=21), n_jobs=-1,
             param_grid={'class_weight': ['balanced', None],
                         'criterion': ['entropy', 'gini'],
                         'max_depth': range(1, 50)},
             scoring='accuracy')

In [12]:
print(f'Лучшие параметры: {grid_search_tree.best_params_}')
print(f'Accuracy на кросс-валидации: {grid_search_tree.best_score_}')

Лучшие параметры: {'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': 21}
Accuracy на кросс-валидации: 0.873864794162192

In [13]:
results_tree = pd.DataFrame(grid_search_tree.cv_results_)
cols = ['param_max_depth', 'param_class_weight', 'param_criterion', 'mean_test_score', 'std_test_score', 'rank_test_score']
results_tree = results_tree[cols].sort_values(['rank_test_score', 'param_max_depth'])
results_tree

,param_max_depth,param_class_weight,param_criterion,mean_test_score,std_test_score,rank_test_score
69,21,balanced,gini,0.873865,0.025066,1
73,25,balanced,gini,0.873854,0.025018,2
70,22,balanced,gini,0.872378,0.025263,3
71,23,balanced,gini,0.872372,0.025179,4
75,27,balanced,gini,0.872372,0.025179,4
76,28,balanced,gini,0.872372,0.025179,4
77,29,balanced,gini,0.872372,0.025179,4
78,30,balanced,gini,0.872372,0.025179,4
79,31,balanced,gini,0.872372,0.025179,4
80,32,balanced,gini,0.872372,0.025179,4
81,33,balanced,gini,0.872372,0.025179,4
82,34,balanced,gini,0.872372,0.025179,4
83,35,balanced,gini,0.872372,0.025179,4
84,36,balanced,gini,0.872372,0.025179,4
85,37,balanced,gini,0.872372,0.025179,4
86,38,balanced,gini,0.872372,0.025179,4
87,39,balanced,gini,0.872372,0.025179,4
88,40,balanced,gini,0.872372,0.025179,4
89,41,balanced,gini,0.872372,0.025179,4
90,42,balanced,gini,0.872372,0.025179,4
91,43,balanced,gini,0.872372,0.025179,4
92,44,balanced,gini,0.872372,0.025179,4
93,45,balanced,gini,0.872372,0.025179,4
94,46,balanced,gini,0.872372,0.025179,4
95,47,balanced,gini,0.872372,0.025179,4
96,48,balanced,gini,0.872372,0.025179,4
97,49,balanced,gini,0.872372,0.025179,4
72,24,balanced,gini,0.871632,0.025390,28
74,26,balanced,gini,0.871632,0.025390,28
68,20,balanced,gini,0.870891,0.027037,30
167,21,None,gini,0.868666,0.019918,31
19,20,balanced,entropy,0.867947,0.010721,32
23,24,balanced,entropy,0.867944,0.013080,33
24,25,balanced,entropy,0.867944,0.013080,33
166,20,None,gini,0.867922,0.020747,35
25,26,balanced,entropy,0.867204,0.013236,36
26,27,balanced,entropy,0.867204,0.013236,36
27,28,balanced,entropy,0.867204,0.013236,36
28,29,balanced,entropy,0.867204,0.013236,36
29,30,balanced,entropy,0.867204,0.013236,36
30,31,balanced,entropy,0.867204,0.013236,36
31,32,balanced,entropy,0.867204,0.013236,36
32,33,balanced,entropy,0.867204,0.013236,36
33,34,balanced,entropy,0.867204,0.013236,36
34,35,balanced,entropy,0.867204,0.013236,36
35,36,balanced,entropy,0.867204,0.013236,36
36,37,balanced,entropy,0.867204,0.013236,36
37,38,balanced,entropy,0.867204,0.013236,36
38,39,balanced,entropy,0.867204,0.013236,36
39,40,balanced,entropy,0.867204,0.013236,36
40,41,balanced,entropy,0.867204,0.013236,36
41,42,balanced,entropy,0.867204,0.013236,36
42,43,balanced,entropy,0.867204,0.013236,36
43,44,balanced,entropy,0.867204,0.013236,36
44,45,balanced,entropy,0.867204,0.013236,36
45,46,balanced,entropy,0.867204,0.013236,36
46,47,balanced,entropy,0.867204,0.013236,36
47,48,balanced,entropy,0.867204,0.013236,36
48,49,balanced,entropy,0.867204,0.013236,36
164,18,None,gini,0.867190,0.019549,60
66,18,balanced,gini,0.867187,0.025963,61
21,22,balanced,entropy,0.866460,0.012523,62
168,22,None,gini,0.866446,0.016617,63
67,19,balanced,gini,0.866444,0.023250,64
165,19,None,gini,0.866441,0.018689,65
17,18,balanced,entropy,0.865719,0.010700,66
118,21,None,entropy,0.865711,0.015946,67
22,23,balanced,entropy,0.864979,0.015207,68
169,23,None,gini,0.864968,0.012747,69
20,21,balanced,entropy,0.864238,0.015729,70
170,24,None,gini,0.864224,0.015314,71
18,19,balanced,entropy,0.863497,0.007996,72
171,25,None,gini,0.863483,0.014531,73
172,26,None,gini,0.863483,0.014531,73
173,27,None,gini,0.863483,0.014531,73
174,28,None,gini,0.863483,0.014531,73
175,29,None,gini,0.863483,0.014531,73
176,30,None,gini,0.863483,0.014531,73
177,31,None,gini,0.863483,0.014531,73
178,32,None,gini,0.863483,0.014531,73
179,33,None,gini,0.863483,0.014531,73
180,34,None,gini,0.863483,0.014531,73
181,35,None,gini,0.863483,0.014531,73
182,36,None,gini,0.863483,0.014531,73
183,37,None,gini,0.863483,0.014531,73
184,38,None,gini,0.863483,0.014531,73
185,39,None,gini,0.863483,0.014531,73
186,40,None,gini,0.863483,0.014531,73
187,41,None,gini,0.863483,0.014531,73
188,42,None,gini,0.863483,0.014531,73
189,43,None,gini,0.863483,0.014531,73
190,44,None,gini,0.863483,0.014531,73
191,45,None,gini,0.863483,0.014531,73
192,46,None,gini,0.863483,0.014531,73
193,47,None,gini,0.863483,0.014531,73
194,48,None,gini,0.863483,0.014531,73
195,49,None,gini,0.863483,0.014531,73
121,24,None,entropy,0.862751,0.019843,98
123,26,None,entropy,0.862007,0.020990,99
124,27,None,entropy,0.862007,0.020990,99
125,28,None,entropy,0.862007,0.020990,99
126,29,None,entropy,0.862007,0.020990,99
127,30,None,entropy,0.862007,0.020990,99
128,31,None,entropy,0.862007,0.020990,99
129,32,None,entropy,0.862007,0.020990,99
130,33,None,entropy,0.862007,0.020990,99
131,34,None,entropy,0.862007,0.020990,99
132,35,None,entropy,0.862007,0.020990,99
133,36,None,entropy,0.862007,0.020990,99
134,37,None,entropy,0.862007,0.020990,99
135,38,None,entropy,0.862007,0.020990,99
136,39,None,entropy,0.862007,0.020990,99
137,40,None,entropy,0.862007,0.020990,99
138,41,None,entropy,0.862007,0.020990,99
139,42,None,entropy,0.862007,0.020990,99
140,43,None,entropy,0.862007,0.020990,99
141,44,None,entropy,0.862007,0.020990,99
142,45,None,entropy,0.862007,0.020990,99
143,46,None,entropy,0.862007,0.020990,99
144,47,None,entropy,0.862007,0.020990,99
145,48,None,entropy,0.862007,0.020990,99
146,49,None,entropy,0.862007,0.020990,99
65,17,balanced,gini,0.861983,0.030959,123
16,17,balanced,entropy,0.861261,0.014535,124
122,25,None,entropy,0.860526,0.022146,125
119,22,None,entropy,0.859782,0.016229,126
120,23,None,entropy,0.859777,0.021022,127
116,19,None,entropy,0.859042,0.009812,128
117,20,None,entropy,0.857555,0.013936,129
15,16,balanced,entropy,0.855335,0.010056,130
64,16,balanced,gini,0.851604,0.024665,131
163,17,None,gini,0.850861,0.026855,132
162,16,None,gini,0.849382,0.028913,133
14,15,balanced,entropy,0.848663,0.009542,134
63,15,balanced,gini,0.846411,0.025958,135
115,18,None,entropy,0.844954,0.014752,136
114,17,None,entropy,0.843467,0.019881,137
112,15,None,entropy,0.840490,0.024849,138
113,16,None,entropy,0.836786,0.020143,139
161,15,None,gini,0.836770,0.028980,140
62,14,balanced,gini,0.836018,0.028708,141
13,14,balanced,entropy,0.835308,0.011918,142
111,14,None,entropy,0.829382,0.028473,143
160,14,None,gini,0.829338,0.032321,144
61,13,balanced,gini,0.823404,0.027491,145
110,13,None,entropy,0.818978,0.023290,146
12,13,balanced,entropy,0.814537,0.014289,147
11,12,balanced,entropy,0.813063,0.011290,148
159,13,None,gini,0.811524,0.033350,149
109,12,None,entropy,0.803393,0.029366,150
10,11,balanced,entropy,0.796740,0.021240,151
60,12,balanced,gini,0.794482,0.029206,152
158,12,None,gini,0.793697,0.041926,153
108,11,None,entropy,0.775189,0.028698,154
59,11,balanced,gini,0.767027,0.036853,155
157,11,None,gini,0.762547,0.037004,156
9,10,balanced,entropy,0.759637,0.013281,157
107,10,None,entropy,0.744753,0.040568,158
8,9,balanced,entropy,0.736665,0.016292,159
156,10,None,gini,0.727702,0.029483,160
58,10,balanced,gini,0.726972,0.051932,161
106,9,None,entropy,0.706934,0.026884,162
57,9,balanced,gini,0.694355,0.043393,163
155,9,None,gini,0.689855,0.032002,164
7,8,balanced,entropy,0.675065,0.017206,165
105,8,None,entropy,0.668357,0.027708,166
154,8,None,gini,0.660947,0.017797,167
56,8,balanced,gini,0.643145,0.053449,168
104,7,None,entropy,0.641641,0.032264,169
153,7,None,gini,0.635729,0.016429,170
6,7,balanced,entropy,0.630558,0.028530,171
55,7,balanced,gini,0.615688,0.053886,172
152,6,None,gini,0.600867,0.023676,173
103,6,None,entropy,0.579339,0.021800,174
5,6,balanced,entropy,0.577871,0.012992,175
54,6,balanced,gini,0.571150,0.060838,176
151,5,None,gini,0.548936,0.026814,177
102,5,None,entropy,0.530409,0.021850,178
150,4,None,gini,0.513322,0.026414,179
53,5,balanced,gini,0.502952,0.056363,180
4,5,balanced,entropy,0.493284,0.034758,181
101,4,None,entropy,0.488107,0.014701,182
149,3,None,gini,0.468809,0.024804,183
100,3,None,entropy,0.448806,0.015866,184
52,4,balanced,gini,0.445830,0.060496,185
148,2,None,gini,0.427278,0.024602,186
3,4,balanced,entropy,0.424343,0.042960,187
99,2,None,entropy,0.398367,0.026750,188
1,2,balanced,entropy,0.385783,0.022437,189
50,2,balanced,gini,0.385783,0.022437,189
2,3,balanced,entropy,0.382834,0.038629,191
51,3,balanced,gini,0.373906,0.044064,192
98,1,None,entropy,0.355330,0.009338,193
147,1,None,gini,0.355330,0.009338,193
0,1,balanced,entropy,0.286358,0.028376,195
49,1,balanced,gini,0.286358,0.028376,195

**Выводы**: Разница между первым и вторым местом составляет сотые процента, хотя глубина лучшей модели на 4 меньше. Так же существуют группы моделей с одинаковым скором, но с разной глубиной дерева. Это следствие того, что дерево при комбинации class_weight и criterion достигает своей естественной максимальной глубины раньше, чем max_depth начинает реально ограничивать рост (то есть дерево останавливается само - все листья становятся чистыми или упираются в другие критерии остановки). Поэтому любое значение max_depth, большее этой фактической глубины, попросту не влияет на итоговое дерево — получается идентичная модель, посчитанная многократно

## 4. Random forest

1. Using `GridSearchCV` try different parameters of `n_estimators` (`5`, `10`, `50`, `100`), `max_depth` (from `1` to `49`), `class_weight` (`balanced`, `None`) and `criterion` (`entropy` and `gini`) and get the best combination of them in terms of accuracy. Use random_state=21.
2. Create a dataframe from the results of the gridsearch and sort it ascendengly by the `rank_test_score`, check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [14]:
params_forest = {
    'n_estimators': [5, 10, 50, 100],
    'max_depth': range(1, 50),
    'class_weight': ['balanced', None],
    'criterion': ['entropy', 'gini']
}

forest = RandomForestClassifier(random_state=RANDOM_STATE)

grid_search_forest = GridSearchCV(
    forest,
    params_forest,
    scoring='accuracy',
    n_jobs=-1
)

grid_search_forest.fit(X_train, y_train)

GridSearchCV(estimator=RandomForestClassifier(random_state=21), n_jobs=-1,
             param_grid={'class_weight': ['balanced', None],
                         'criterion': ['entropy', 'gini'],
                         'max_depth': range(1, 50),
                         'n_estimators': [5, 10, 50, 100]},
             scoring='accuracy')

In [15]:
print(f'Лучшие параметры: {grid_search_forest.best_params_}')
print(f'Accuracy на кросс-валидации: {grid_search_forest.best_score_}')

Лучшие параметры: {'class_weight': 'balanced', 'criterion': 'entropy', 'max_depth': 24, 'n_estimators': 100}
Accuracy на кросс-валидации: 0.9042929918766351

In [16]:
results_forest = pd.DataFrame(grid_search_forest.cv_results_)
cols = ['param_n_estimators', 'param_max_depth', 'param_class_weight', 'param_criterion', 'mean_test_score', 'std_test_score', 'rank_test_score']
results_forest = results_forest[cols].sort_values(['rank_test_score'])
results_forest

,param_n_estimators,param_max_depth,param_class_weight,param_criterion,mean_test_score,std_test_score,rank_test_score
95,100,24,balanced,entropy,0.904293,0.012361,1
115,100,29,balanced,entropy,0.904290,0.012156,2
698,50,28,None,gini,0.904290,0.010961,2
314,50,30,balanced,gini,0.903549,0.012056,4
711,100,31,None,gini,0.903547,0.014380,5
99,100,25,balanced,entropy,0.902809,0.013639,6
326,50,33,balanced,gini,0.902809,0.013628,7
767,100,45,None,gini,0.902806,0.010460,8
779,100,48,None,gini,0.902806,0.010460,8
775,100,47,None,gini,0.902806,0.010460,8
771,100,46,None,gini,0.902806,0.010460,8
702,50,29,None,gini,0.902806,0.011698,8
731,100,36,None,gini,0.902806,0.010460,8
735,100,37,None,gini,0.902806,0.010460,8
739,100,38,None,gini,0.902806,0.010460,8
743,100,39,None,gini,0.902806,0.010460,8
747,100,40,None,gini,0.902806,0.010460,8
783,100,49,None,gini,0.902806,0.010460,8
751,100,41,None,gini,0.902806,0.010460,8
763,100,44,None,gini,0.902806,0.010460,8
755,100,42,None,gini,0.902806,0.010460,8
759,100,43,None,gini,0.902806,0.010460,8
707,100,30,None,gini,0.902068,0.012843,23
723,100,34,None,gini,0.902065,0.010759,24
706,50,30,None,gini,0.902063,0.011989,25
766,50,45,None,gini,0.902063,0.014494,26
778,50,48,None,gini,0.902063,0.014494,26
774,50,47,None,gini,0.902063,0.014494,26
750,50,41,None,gini,0.902063,0.014494,26
762,50,44,None,gini,0.902063,0.014494,26
770,50,46,None,gini,0.902063,0.014494,26
710,50,31,None,gini,0.902063,0.016119,26
746,50,40,None,gini,0.902063,0.014494,26
734,50,37,None,gini,0.902063,0.014494,26
754,50,42,None,gini,0.902063,0.014494,26
738,50,38,None,gini,0.902063,0.014494,26
742,50,39,None,gini,0.902063,0.014494,26
727,100,35,None,gini,0.902063,0.011767,26
730,50,36,None,gini,0.902063,0.014494,26
758,50,43,None,gini,0.902063,0.014494,26
782,50,49,None,gini,0.902063,0.014494,26
330,50,34,balanced,gini,0.901327,0.015354,42
691,100,26,None,gini,0.901327,0.011225,42
703,100,29,None,gini,0.901327,0.012834,44
131,100,33,balanced,entropy,0.901325,0.013890,45
322,50,32,balanced,gini,0.901322,0.014850,46
107,100,27,balanced,entropy,0.901322,0.015225,46
715,100,32,None,gini,0.901319,0.013524,48
722,50,34,None,gini,0.901316,0.015798,49
311,100,29,balanced,gini,0.900587,0.013204,50
687,100,25,None,gini,0.900587,0.007657,50
306,50,28,balanced,gini,0.900581,0.013659,52
719,100,33,None,gini,0.900581,0.010974,52
111,100,28,balanced,entropy,0.900576,0.017103,54
726,50,35,None,gini,0.900576,0.014859,54
71,100,18,balanced,entropy,0.900576,0.018039,54
315,100,30,balanced,gini,0.899849,0.013509,57
334,50,35,balanced,gini,0.899846,0.015411,58
338,50,36,balanced,gini,0.899846,0.015411,58
690,50,26,None,gini,0.899843,0.010302,60
302,50,27,balanced,gini,0.899843,0.017459,60
310,50,29,balanced,gini,0.899843,0.014340,60
94,50,24,balanced,entropy,0.899843,0.012278,60
83,100,21,balanced,entropy,0.899843,0.012704,64
675,100,22,None,gini,0.899843,0.013940,64
123,100,31,balanced,entropy,0.899843,0.012487,64
471,100,20,None,entropy,0.899843,0.014328,64
307,100,28,balanced,gini,0.899840,0.017483,68
135,100,34,balanced,entropy,0.899840,0.013569,68
119,100,30,balanced,entropy,0.899840,0.013968,68
103,100,26,balanced,entropy,0.899838,0.015836,71
127,100,32,balanced,entropy,0.899838,0.014760,72
714,50,32,None,gini,0.899835,0.013198,73
686,50,25,None,gini,0.899835,0.014391,73
79,100,20,balanced,entropy,0.899829,0.019474,75
374,50,45,balanced,gini,0.899105,0.014179,76
346,50,38,balanced,gini,0.899105,0.014179,76
382,50,47,balanced,gini,0.899105,0.014179,76
366,50,43,balanced,gini,0.899105,0.014179,76
370,50,44,balanced,gini,0.899105,0.014179,76
318,50,31,balanced,gini,0.899105,0.014933,76
386,50,48,balanced,gini,0.899105,0.014179,76
354,50,40,balanced,gini,0.899105,0.014179,76
390,50,49,balanced,gini,0.899105,0.014179,76
362,50,42,balanced,gini,0.899105,0.014179,76
342,50,37,balanced,gini,0.899105,0.014179,76
358,50,41,balanced,gini,0.899105,0.014179,76
378,50,46,balanced,gini,0.899105,0.014179,76
350,50,39,balanced,gini,0.899105,0.014179,76
299,100,26,balanced,gini,0.899102,0.015848,90
683,100,24,None,gini,0.899102,0.011659,90
295,100,25,balanced,gini,0.899100,0.014811,92
699,100,28,None,gini,0.899100,0.013841,93
78,50,20,balanced,entropy,0.899097,0.016586,94
279,100,21,balanced,gini,0.899094,0.018177,95
298,50,26,balanced,gini,0.898370,0.012079,96
583,100,48,None,entropy,0.898362,0.014986,97
482,50,23,None,entropy,0.898362,0.013028,97
303,100,27,balanced,gini,0.898362,0.014813,97
587,100,49,None,entropy,0.898362,0.014986,97
555,100,41,None,entropy,0.898362,0.014986,97
579,100,47,None,entropy,0.898362,0.014986,97
531,100,35,None,entropy,0.898362,0.014986,97
563,100,43,None,entropy,0.898362,0.014986,97
535,100,36,None,entropy,0.898362,0.014986,97
567,100,44,None,entropy,0.898362,0.014986,97
539,100,37,None,entropy,0.898362,0.014986,97
547,100,39,None,entropy,0.898362,0.014986,97
543,100,38,None,entropy,0.898362,0.014986,97
571,100,45,None,entropy,0.898362,0.014986,97
575,100,46,None,entropy,0.898362,0.014986,97
559,100,42,None,entropy,0.898362,0.014986,97
551,100,40,None,entropy,0.898362,0.014986,97
327,100,33,balanced,gini,0.898359,0.016914,114
167,100,42,balanced,entropy,0.898359,0.013872,115
159,100,40,balanced,entropy,0.898359,0.013872,115
163,100,41,balanced,entropy,0.898359,0.013872,115
179,100,45,balanced,entropy,0.898359,0.013872,115
187,100,47,balanced,entropy,0.898359,0.013872,115
147,100,37,balanced,entropy,0.898359,0.013872,115
191,100,48,balanced,entropy,0.898359,0.013872,115
195,100,49,balanced,entropy,0.898359,0.013872,115
143,100,36,balanced,entropy,0.898359,0.013872,115
171,100,43,balanced,entropy,0.898359,0.013872,115
151,100,38,balanced,entropy,0.898359,0.013872,115
175,100,44,balanced,entropy,0.898359,0.013872,115
155,100,39,balanced,entropy,0.898359,0.013872,115
139,100,35,balanced,entropy,0.898359,0.013872,115
183,100,46,balanced,entropy,0.898359,0.013872,115
523,100,33,None,entropy,0.898359,0.015373,115
695,100,27,None,gini,0.898359,0.012188,115
291,100,24,balanced,gini,0.898356,0.017260,132
87,100,22,balanced,entropy,0.898356,0.016096,133
67,100,17,balanced,entropy,0.898356,0.013489,133
75,100,19,balanced,entropy,0.898356,0.015576,133
503,100,28,None,entropy,0.898356,0.016096,133
530,50,35,None,entropy,0.898353,0.019381,137
542,50,38,None,entropy,0.898353,0.019381,137
546,50,39,None,entropy,0.898353,0.019381,137
550,50,40,None,entropy,0.898353,0.019381,137
538,50,37,None,entropy,0.898353,0.019381,137
526,50,34,None,entropy,0.898353,0.019381,137
562,50,43,None,entropy,0.898353,0.019381,137
566,50,44,None,entropy,0.898353,0.019381,137
570,50,45,None,entropy,0.898353,0.019381,137
574,50,46,None,entropy,0.898353,0.019381,137
578,50,47,None,entropy,0.898353,0.019381,137
582,50,48,None,entropy,0.898353,0.019381,137
586,50,49,None,entropy,0.898353,0.019381,137
554,50,41,None,entropy,0.898353,0.019381,137
558,50,42,None,entropy,0.898353,0.019381,137
534,50,36,None,entropy,0.898353,0.019381,137
522,50,33,None,entropy,0.898353,0.019381,137
286,50,23,balanced,gini,0.897621,0.010435,154
514,50,31,None,entropy,0.897615,0.020196,155
283,100,22,balanced,gini,0.897615,0.016426,156
515,100,31,None,entropy,0.897615,0.016426,156
518,50,32,None,entropy,0.897613,0.019232,158
63,100,16,balanced,entropy,0.897610,0.016130,159
478,50,22,None,entropy,0.896886,0.011579,160
694,50,27,None,gini,0.896877,0.013798,161
507,100,29,None,entropy,0.896877,0.014399,161
519,100,32,None,entropy,0.896875,0.016880,163
491,100,25,None,entropy,0.896875,0.015348,163
498,50,27,None,entropy,0.896875,0.018145,163
323,100,32,balanced,gini,0.896875,0.014427,163
294,50,25,balanced,gini,0.896872,0.015375,167
718,50,33,None,gini,0.896869,0.015558,168
479,100,22,None,entropy,0.896142,0.012411,169
130,50,33,balanced,entropy,0.896137,0.016129,170
483,100,23,None,entropy,0.896137,0.014878,171
86,50,22,balanced,entropy,0.896137,0.014504,171
679,100,23,None,gini,0.896137,0.012248,171
319,100,31,balanced,gini,0.896134,0.016656,174
275,100,20,balanced,gini,0.896134,0.013144,175
511,100,30,None,entropy,0.896134,0.016808,175
74,50,19,balanced,entropy,0.896131,0.017486,177
667,100,20,None,gini,0.896131,0.014156,177
474,50,21,None,entropy,0.896131,0.016350,177
495,100,26,None,entropy,0.896131,0.016504,177
527,100,34,None,entropy,0.896131,0.017938,177
475,100,21,None,entropy,0.896128,0.018128,182
91,100,23,balanced,entropy,0.896128,0.014949,182
266,50,18,balanced,gini,0.896126,0.017667,184
282,50,22,balanced,gini,0.896123,0.020695,185
278,50,21,balanced,gini,0.896120,0.017708,186
490,50,25,None,entropy,0.895396,0.017189,187
134,50,34,balanced,entropy,0.895396,0.016853,187
142,50,36,balanced,entropy,0.895396,0.016853,187
339,100,36,balanced,gini,0.895393,0.016550,190
335,100,35,balanced,gini,0.895393,0.016550,190
331,100,34,balanced,gini,0.895393,0.016550,190
510,50,30,None,entropy,0.895390,0.020444,193
506,50,29,None,entropy,0.895390,0.018444,193
194,50,49,balanced,entropy,0.894655,0.016716,195
186,50,47,balanced,entropy,0.894655,0.016716,195
178,50,45,balanced,entropy,0.894655,0.016716,195
114,50,29,balanced,entropy,0.894655,0.014614,195
190,50,48,balanced,entropy,0.894655,0.016716,195
174,50,44,balanced,entropy,0.894655,0.016716,195
138,50,35,balanced,entropy,0.894655,0.016716,195
170,50,43,balanced,entropy,0.894655,0.016716,195
146,50,37,balanced,entropy,0.894655,0.016716,195
150,50,38,balanced,entropy,0.894655,0.016716,195
154,50,39,balanced,entropy,0.894655,0.016716,195
182,50,46,balanced,entropy,0.894655,0.016716,195
158,50,40,balanced,entropy,0.894655,0.016716,195
162,50,41,balanced,entropy,0.894655,0.016716,195
166,50,42,balanced,entropy,0.894655,0.016716,195
371,100,44,balanced,gini,0.894652,0.015726,210
363,100,42,balanced,gini,0.894652,0.015726,210
347,100,38,balanced,gini,0.894652,0.015726,210
379,100,46,balanced,gini,0.894652,0.015726,210
383,100,47,balanced,gini,0.894652,0.015726,210
359,100,41,balanced,gini,0.894652,0.015726,210
387,100,48,balanced,gini,0.894652,0.015726,210
355,100,40,balanced,gini,0.894652,0.015726,210
343,100,37,balanced,gini,0.894652,0.015726,210
351,100,39,balanced,gini,0.894652,0.015726,210
367,100,43,balanced,gini,0.894652,0.015726,210
375,100,45,balanced,gini,0.894652,0.015726,210
391,100,49,balanced,gini,0.894652,0.015726,210
122,50,31,balanced,entropy,0.894652,0.016229,210
486,50,24,None,entropy,0.894650,0.013875,224
271,100,19,balanced,gini,0.894650,0.015375,224
287,100,23,balanced,gini,0.894650,0.014265,224
70,50,18,balanced,entropy,0.894650,0.012848,224
678,50,23,None,gini,0.894647,0.011012,228
494,50,26,None,entropy,0.894647,0.017733,228
274,50,20,balanced,gini,0.894647,0.015767,228
663,100,19,None,gini,0.894644,0.017276,231
670,50,21,None,gini,0.894641,0.018675,232
470,50,20,None,entropy,0.894636,0.017954,233
126,50,32,balanced,entropy,0.893912,0.014431,234
487,100,24,None,entropy,0.893909,0.015172,235
499,100,27,None,entropy,0.893906,0.016429,236
671,100,21,None,gini,0.893906,0.013483,236
290,50,24,balanced,gini,0.893901,0.021431,238
110,50,28,balanced,entropy,0.893901,0.020623,239
485,10,24,None,entropy,0.893171,0.014750,240
682,50,24,None,gini,0.893171,0.012746,240
317,10,31,balanced,gini,0.893168,0.022328,242
674,50,22,None,gini,0.893165,0.015350,243
118,50,30,balanced,entropy,0.893165,0.016719,243
98,50,25,balanced,entropy,0.893165,0.015890,245
267,100,18,balanced,gini,0.893163,0.016246,246
59,100,15,balanced,entropy,0.893157,0.015412,247
82,50,21,balanced,entropy,0.892427,0.015435,248
106,50,27,balanced,entropy,0.892425,0.016157,249
502,50,28,None,entropy,0.892422,0.019561,250
659,100,18,None,gini,0.892416,0.015501,251
263,100,17,balanced,gini,0.891687,0.012318,252
655,100,17,None,gini,0.891684,0.008987,253
85,10,22,balanced,entropy,0.891678,0.024801,254
463,100,18,None,entropy,0.891673,0.017597,255
90,50,23,balanced,entropy,0.891670,0.019118,256
93,10,24,balanced,entropy,0.890946,0.014964,257
313,10,30,balanced,gini,0.890946,0.023649,257
62,50,16,balanced,entropy,0.890940,0.017854,259
102,50,26,balanced,entropy,0.890940,0.016087,259
297,10,26,balanced,gini,0.890940,0.011954,259
666,50,20,None,gini,0.890938,0.011016,262
493,10,26,None,entropy,0.890932,0.023139,263
353,10,40,balanced,gini,0.890200,0.022492,264
345,10,38,balanced,gini,0.890200,0.022492,264
365,10,43,balanced,gini,0.890200,0.022492,264
357,10,41,balanced,gini,0.890200,0.022492,264
341,10,37,balanced,gini,0.890200,0.022492,264
389,10,49,balanced,gini,0.890200,0.022492,264
337,10,36,balanced,gini,0.890200,0.022492,264
369,10,44,balanced,gini,0.890200,0.022492,264
333,10,35,balanced,gini,0.890200,0.022492,264
361,10,42,balanced,gini,0.890200,0.022492,264
329,10,34,balanced,gini,0.890200,0.022492,264
385,10,48,balanced,gini,0.890200,0.022492,264
381,10,47,balanced,gini,0.890200,0.022492,264
325,10,33,balanced,gini,0.890200,0.022492,264
349,10,39,balanced,gini,0.890200,0.022492,264
373,10,45,balanced,gini,0.890200,0.022492,264
377,10,46,balanced,gini,0.890200,0.022492,264
66,50,17,balanced,entropy,0.890194,0.015247,281
58,50,15,balanced,entropy,0.890194,0.012001,282
270,50,19,balanced,gini,0.889459,0.012990,283
662,50,19,None,gini,0.889448,0.019361,284
305,10,28,balanced,gini,0.888724,0.016443,285
321,10,32,balanced,gini,0.888718,0.021533,286
309,10,29,balanced,gini,0.888718,0.025831,286
262,50,17,balanced,gini,0.888715,0.012702,288
255,100,15,balanced,gini,0.888713,0.014917,289
462,50,18,None,entropy,0.888710,0.018100,290
455,100,16,None,entropy,0.888707,0.016706,291
665,10,20,None,gini,0.887983,0.015258,292
467,100,19,None,entropy,0.887972,0.019613,293
258,50,16,balanced,gini,0.887972,0.018725,293
654,50,17,None,gini,0.887972,0.012360,295
259,100,16,balanced,gini,0.887964,0.013708,296
497,10,27,None,entropy,0.887239,0.021589,297
693,10,27,None,gini,0.887239,0.016517,297
501,10,28,None,entropy,0.887237,0.019448,299
69,10,18,balanced,entropy,0.887231,0.021871,300
454,50,16,None,entropy,0.887231,0.020049,300
97,10,25,balanced,entropy,0.887228,0.021367,302
697,10,28,None,gini,0.887228,0.016442,302
459,100,17,None,entropy,0.887223,0.018386,304
505,10,29,None,entropy,0.886499,0.017644,305
285,10,23,balanced,gini,0.886490,0.020821,306
513,10,31,None,entropy,0.886488,0.021497,307
312,5,30,balanced,gini,0.886485,0.030692,308
469,10,20,None,entropy,0.885752,0.007265,309
529,10,35,None,entropy,0.885752,0.018690,309
517,10,32,None,entropy,0.885750,0.019712,311
161,10,41,balanced,entropy,0.885747,0.019586,312
193,10,49,balanced,entropy,0.885747,0.019586,312
153,10,39,balanced,entropy,0.885747,0.019586,312
141,10,36,balanced,entropy,0.885747,0.019586,312
185,10,47,balanced,entropy,0.885747,0.019586,312
181,10,46,balanced,entropy,0.885747,0.019586,312
169,10,43,balanced,entropy,0.885747,0.019586,312
165,10,42,balanced,entropy,0.885747,0.019586,312
177,10,45,balanced,entropy,0.885747,0.019586,312
149,10,38,balanced,entropy,0.885747,0.019586,312
137,10,35,balanced,entropy,0.885747,0.019586,312
173,10,44,balanced,entropy,0.885747,0.019586,312
189,10,48,balanced,entropy,0.885747,0.019586,312
145,10,37,balanced,entropy,0.885747,0.019586,312
157,10,40,balanced,entropy,0.885747,0.019586,312
105,10,27,balanced,entropy,0.885747,0.021953,312
89,10,23,balanced,entropy,0.885744,0.014624,328
461,10,18,None,entropy,0.885744,0.020288,329
466,50,19,None,entropy,0.885739,0.023271,330
473,10,21,None,entropy,0.885739,0.015784,330
537,10,37,None,entropy,0.885012,0.018476,332
533,10,36,None,entropy,0.885012,0.018476,332
521,10,33,None,entropy,0.885012,0.018476,332
301,10,27,balanced,gini,0.885012,0.024739,332
289,10,24,balanced,gini,0.885006,0.022183,336
651,100,16,None,gini,0.885006,0.013562,336
121,10,31,balanced,entropy,0.885006,0.018952,336
293,10,25,balanced,gini,0.885003,0.027825,339
477,10,22,None,entropy,0.884268,0.013982,340
55,100,14,balanced,entropy,0.884268,0.012770,340
125,10,32,balanced,entropy,0.884265,0.018417,342
129,10,33,balanced,entropy,0.884265,0.018417,342
458,50,17,None,entropy,0.884263,0.016570,344
701,10,29,None,gini,0.884257,0.014101,345
451,100,15,None,entropy,0.884254,0.016957,346
481,10,23,None,entropy,0.884254,0.024631,346
472,5,21,None,entropy,0.884246,0.019299,348
549,10,40,None,entropy,0.883530,0.018403,349
545,10,39,None,entropy,0.883530,0.018403,349
541,10,38,None,entropy,0.883530,0.018403,349
581,10,48,None,entropy,0.883530,0.018403,349
577,10,47,None,entropy,0.883530,0.018403,349
573,10,46,None,entropy,0.883530,0.018403,349
553,10,41,None,entropy,0.883530,0.018403,349
557,10,42,None,entropy,0.883530,0.018403,349
565,10,44,None,entropy,0.883530,0.018403,349
561,10,43,None,entropy,0.883530,0.018403,349
585,10,49,None,entropy,0.883530,0.018403,349
569,10,45,None,entropy,0.883530,0.018403,349
509,10,30,None,entropy,0.883525,0.019880,361
113,10,29,balanced,entropy,0.883525,0.017524,361
705,10,30,None,gini,0.883525,0.020164,361
484,5,24,None,entropy,0.883525,0.016391,361
133,10,34,balanced,entropy,0.883525,0.017987,361
117,10,30,balanced,entropy,0.883522,0.019191,366
713,10,32,None,gini,0.883522,0.018155,367
528,5,35,None,entropy,0.883522,0.023815,367
500,5,28,None,entropy,0.883519,0.024293,369
689,10,26,None,gini,0.883519,0.018658,369
658,50,18,None,gini,0.883514,0.017771,371
81,10,21,balanced,entropy,0.883508,0.022326,372
277,10,21,balanced,gini,0.883508,0.017969,373
669,10,21,None,gini,0.882787,0.010132,374
525,10,34,None,entropy,0.882784,0.019734,375
536,5,37,None,entropy,0.882781,0.023810,376
532,5,36,None,entropy,0.882781,0.023810,376
254,50,15,balanced,gini,0.882776,0.020205,378
709,10,31,None,gini,0.882776,0.015772,379
73,10,19,balanced,entropy,0.882773,0.020922,380
109,10,28,balanced,entropy,0.882773,0.019379,380
281,10,22,balanced,gini,0.882770,0.022205,382
677,10,23,None,gini,0.882043,0.016002,383
673,10,22,None,gini,0.882038,0.020707,384
77,10,20,balanced,entropy,0.882038,0.017552,384
761,10,44,None,gini,0.882035,0.019749,386
741,10,39,None,gini,0.882035,0.019749,386
749,10,41,None,gini,0.882035,0.019749,386
737,10,38,None,gini,0.882035,0.019749,386
733,10,37,None,gini,0.882035,0.019749,386
721,10,34,None,gini,0.882035,0.019749,386
757,10,43,None,gini,0.882035,0.019749,386
745,10,40,None,gini,0.882035,0.019749,386
725,10,35,None,gini,0.882035,0.019749,386
753,10,42,None,gini,0.882035,0.019749,386
765,10,45,None,gini,0.882035,0.019749,386
650,50,16,None,gini,0.882035,0.018919,386
781,10,49,None,gini,0.882035,0.019749,386
777,10,48,None,gini,0.882035,0.019749,386
729,10,36,None,gini,0.882035,0.019749,386
54,50,14,balanced,entropy,0.882035,0.013676,386
773,10,47,None,gini,0.882035,0.019749,386
769,10,46,None,gini,0.882035,0.019749,386
450,50,15,None,entropy,0.882032,0.017878,404
520,5,33,None,entropy,0.881300,0.024073,405
717,10,33,None,gini,0.881294,0.017775,406
584,5,49,None,entropy,0.880559,0.024340,407
548,5,40,None,entropy,0.880559,0.024340,407
580,5,48,None,entropy,0.880559,0.024340,407
576,5,47,None,entropy,0.880559,0.024340,407
540,5,38,None,entropy,0.880559,0.024340,407
504,5,29,None,entropy,0.880559,0.021970,407
572,5,46,None,entropy,0.880559,0.024340,407
560,5,43,None,entropy,0.880559,0.024340,407
568,5,45,None,entropy,0.880559,0.024340,407
564,5,44,None,entropy,0.880559,0.024340,407
544,5,39,None,entropy,0.880559,0.024340,407
556,5,42,None,entropy,0.880559,0.024340,407
552,5,41,None,entropy,0.880559,0.024340,407
316,5,31,balanced,gini,0.880559,0.025454,420
251,100,14,balanced,gini,0.880556,0.015667,421
647,100,15,None,gini,0.880556,0.019180,422
447,100,14,None,entropy,0.880542,0.021665,423
296,5,26,balanced,gini,0.879821,0.017663,424
453,10,16,None,entropy,0.879813,0.021001,425
512,5,31,None,entropy,0.879813,0.026031,425
273,10,20,balanced,gini,0.879810,0.026868,427
51,100,13,balanced,entropy,0.879810,0.017757,427
465,10,19,None,entropy,0.879807,0.026192,429
47,100,12,balanced,entropy,0.879807,0.020761,430
516,5,32,None,entropy,0.879807,0.028098,430
489,10,25,None,entropy,0.879086,0.018394,432
508,5,30,None,entropy,0.879078,0.022354,433
304,5,28,balanced,gini,0.879075,0.024596,434
250,50,14,balanced,gini,0.879069,0.017076,435
101,10,26,balanced,entropy,0.879069,0.018014,435
288,5,24,balanced,gini,0.879064,0.025450,437

**Выводы**: Лучшая комбинация - n_estimators=100, max_depth=24, class_weight='balanced', criterion='entropy' (accuracy примерно 0.904), но разница между топовыми моделями минимальна (~0.003) - можно смело брать более простую модель без потери качества. Критично важна только глубина: при max_depth <= 5 accuracy резко падает, независимо от остальных параметров. class_weight и criterion почти не влияют на результат

## 5. Progress bar

Gridsearch can be a quite long process and you may find yourself wondering when it will end.
1. Create a manual gridsearch for the same parameters values of random forest iterating through the list of the possible values and calculating `cross_val_score` for each combination. Try to increase `n_jobs`. The value `cv` for `cross_val_score` is 5.
2. Track the progress using the library `tqdm.notebook`.
3. Create a dataframe from the results of the gridsearch with the columns corresponding to the names of the parameters and `mean_accuracy` and `std_accuracy`.
4. Sort it descendingly by the `mean_accuracy`, check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [17]:
keys = list(params_forest.keys())
values = list(params_forest.values())

combinations = list(itertools.product(*values))
results = []

for combo in tqdm(combinations):
    params = dict(zip(keys, combo))
    model = RandomForestClassifier(
        **params,
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
    
    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=5,
        n_jobs=-1
    )
    
    results.append({
        **params,
        "mean_accuracy": scores.mean(),
        "std_accuracy": scores.std()
    })

  0%|          | 0/784 [00:00<?, ?it/s]

In [18]:
df_results = pd.DataFrame(results)
df_results = df_results.sort_values(by='mean_accuracy', ascending=False)
df_results

,n_estimators,max_depth,class_weight,criterion,mean_accuracy,std_accuracy
680,100,24,balanced,entropy,0.904293,0.012361
503,50,28,None,gini,0.904290,0.010961
700,100,29,balanced,entropy,0.904290,0.012156
509,50,30,balanced,gini,0.903549,0.012056
711,100,31,None,gini,0.903547,0.014380
684,100,25,balanced,entropy,0.902809,0.013639
521,50,33,balanced,gini,0.902809,0.013628
783,100,49,None,gini,0.902806,0.010460
507,50,29,None,gini,0.902806,0.011698
731,100,36,None,gini,0.902806,0.010460
771,100,46,None,gini,0.902806,0.010460
735,100,37,None,gini,0.902806,0.010460
739,100,38,None,gini,0.902806,0.010460
743,100,39,None,gini,0.902806,0.010460
747,100,40,None,gini,0.902806,0.010460
751,100,41,None,gini,0.902806,0.010460
755,100,42,None,gini,0.902806,0.010460
759,100,43,None,gini,0.902806,0.010460
767,100,45,None,gini,0.902806,0.010460
763,100,44,None,gini,0.902806,0.010460
779,100,48,None,gini,0.902806,0.010460
775,100,47,None,gini,0.902806,0.010460
707,100,30,None,gini,0.902068,0.012843
723,100,34,None,gini,0.902065,0.010759
511,50,30,None,gini,0.902063,0.011989
583,50,48,None,gini,0.902063,0.014494
543,50,38,None,gini,0.902063,0.014494
551,50,40,None,gini,0.902063,0.014494
587,50,49,None,gini,0.902063,0.014494
539,50,37,None,gini,0.902063,0.014494
579,50,47,None,gini,0.902063,0.014494
535,50,36,None,gini,0.902063,0.014494
555,50,41,None,gini,0.902063,0.014494
575,50,46,None,gini,0.902063,0.014494
727,100,35,None,gini,0.902063,0.011767
571,50,45,None,gini,0.902063,0.014494
547,50,39,None,gini,0.902063,0.014494
567,50,44,None,gini,0.902063,0.014494
559,50,42,None,gini,0.902063,0.014494
563,50,43,None,gini,0.902063,0.014494
515,50,31,None,gini,0.902063,0.016119
525,50,34,balanced,gini,0.901327,0.015354
691,100,26,None,gini,0.901327,0.011225
703,100,29,None,gini,0.901327,0.012834
716,100,33,balanced,entropy,0.901325,0.013890
692,100,27,balanced,entropy,0.901322,0.015225
517,50,32,balanced,gini,0.901322,0.014850
715,100,32,None,gini,0.901319,0.013524
527,50,34,None,gini,0.901316,0.015798
687,100,25,None,gini,0.900587,0.007657
701,100,29,balanced,gini,0.900587,0.013204
719,100,33,None,gini,0.900581,0.010974
501,50,28,balanced,gini,0.900581,0.013659
696,100,28,balanced,entropy,0.900576,0.017103
656,100,18,balanced,entropy,0.900576,0.018039
531,50,35,None,gini,0.900576,0.014859
705,100,30,balanced,gini,0.899849,0.013509
533,50,36,balanced,gini,0.899846,0.015411
529,50,35,balanced,gini,0.899846,0.015411
495,50,26,None,gini,0.899843,0.010302
505,50,29,balanced,gini,0.899843,0.014340
484,50,24,balanced,entropy,0.899843,0.012278
497,50,27,balanced,gini,0.899843,0.017459
708,100,31,balanced,entropy,0.899843,0.012487
675,100,22,None,gini,0.899843,0.013940
666,100,20,None,entropy,0.899843,0.014328
668,100,21,balanced,entropy,0.899843,0.012704
720,100,34,balanced,entropy,0.899840,0.013569
697,100,28,balanced,gini,0.899840,0.017483
704,100,30,balanced,entropy,0.899840,0.013968
688,100,26,balanced,entropy,0.899838,0.015836
712,100,32,balanced,entropy,0.899838,0.014760
519,50,32,None,gini,0.899835,0.013198
491,50,25,None,gini,0.899835,0.014391
664,100,20,balanced,entropy,0.899829,0.019474
573,50,46,balanced,gini,0.899105,0.014179
565,50,44,balanced,gini,0.899105,0.014179
561,50,43,balanced,gini,0.899105,0.014179
569,50,45,balanced,gini,0.899105,0.014179
557,50,42,balanced,gini,0.899105,0.014179
513,50,31,balanced,gini,0.899105,0.014933
541,50,38,balanced,gini,0.899105,0.014179
581,50,48,balanced,gini,0.899105,0.014179
545,50,39,balanced,gini,0.899105,0.014179
553,50,41,balanced,gini,0.899105,0.014179
549,50,40,balanced,gini,0.899105,0.014179
585,50,49,balanced,gini,0.899105,0.014179
577,50,47,balanced,gini,0.899105,0.014179
537,50,37,balanced,gini,0.899105,0.014179
689,100,26,balanced,gini,0.899102,0.015848
683,100,24,None,gini,0.899102,0.011659
685,100,25,balanced,gini,0.899100,0.014811
699,100,28,None,gini,0.899100,0.013841
468,50,20,balanced,entropy,0.899097,0.016586
669,100,21,balanced,gini,0.899094,0.018177
493,50,26,balanced,gini,0.898370,0.012079
766,100,45,None,entropy,0.898362,0.014986
726,100,35,None,entropy,0.898362,0.014986
770,100,46,None,entropy,0.898362,0.014986
730,100,36,None,entropy,0.898362,0.014986
693,100,27,balanced,gini,0.898362,0.014813
738,100,38,None,entropy,0.898362,0.014986
742,100,39,None,entropy,0.898362,0.014986
482,50,23,None,entropy,0.898362,0.013028
778,100,48,None,entropy,0.898362,0.014986
746,100,40,None,entropy,0.898362,0.014986
750,100,41,None,entropy,0.898362,0.014986
754,100,42,None,entropy,0.898362,0.014986
758,100,43,None,entropy,0.898362,0.014986
782,100,49,None,entropy,0.898362,0.014986
762,100,44,None,entropy,0.898362,0.014986
774,100,47,None,entropy,0.898362,0.014986
734,100,37,None,entropy,0.898362,0.014986
717,100,33,balanced,gini,0.898359,0.016914
718,100,33,None,entropy,0.898359,0.015373
744,100,40,balanced,entropy,0.898359,0.013872
724,100,35,balanced,entropy,0.898359,0.013872
740,100,39,balanced,entropy,0.898359,0.013872
780,100,49,balanced,entropy,0.898359,0.013872
752,100,42,balanced,entropy,0.898359,0.013872
736,100,38,balanced,entropy,0.898359,0.013872
756,100,43,balanced,entropy,0.898359,0.013872
748,100,41,balanced,entropy,0.898359,0.013872
768,100,46,balanced,entropy,0.898359,0.013872
732,100,37,balanced,entropy,0.898359,0.013872
776,100,48,balanced,entropy,0.898359,0.013872
728,100,36,balanced,entropy,0.898359,0.013872
695,100,27,None,gini,0.898359,0.012188
764,100,45,balanced,entropy,0.898359,0.013872
772,100,47,balanced,entropy,0.898359,0.013872
760,100,44,balanced,entropy,0.898359,0.013872
681,100,24,balanced,gini,0.898356,0.017260
672,100,22,balanced,entropy,0.898356,0.016096
652,100,17,balanced,entropy,0.898356,0.013489
660,100,19,balanced,entropy,0.898356,0.015576
698,100,28,None,entropy,0.898356,0.016096
574,50,46,None,entropy,0.898353,0.019381
526,50,34,None,entropy,0.898353,0.019381
570,50,45,None,entropy,0.898353,0.019381
566,50,44,None,entropy,0.898353,0.019381
578,50,47,None,entropy,0.898353,0.019381
554,50,41,None,entropy,0.898353,0.019381
534,50,36,None,entropy,0.898353,0.019381
582,50,48,None,entropy,0.898353,0.019381
558,50,42,None,entropy,0.898353,0.019381
562,50,43,None,entropy,0.898353,0.019381
586,50,49,None,entropy,0.898353,0.019381
530,50,35,None,entropy,0.898353,0.019381
522,50,33,None,entropy,0.898353,0.019381
546,50,39,None,entropy,0.898353,0.019381
542,50,38,None,entropy,0.898353,0.019381
538,50,37,None,entropy,0.898353,0.019381
550,50,40,None,entropy,0.898353,0.019381
481,50,23,balanced,gini,0.897621,0.010435
514,50,31,None,entropy,0.897615,0.020196
673,100,22,balanced,gini,0.897615,0.016426
710,100,31,None,entropy,0.897615,0.016426
518,50,32,None,entropy,0.897613,0.019232
648,100,16,balanced,entropy,0.897610,0.016130
478,50,22,None,entropy,0.896886,0.011579
702,100,29,None,entropy,0.896877,0.014399
499,50,27,None,gini,0.896877,0.013798
713,100,32,balanced,gini,0.896875,0.014427
714,100,32,None,entropy,0.896875,0.016880
498,50,27,None,entropy,0.896875,0.018145
686,100,25,None,entropy,0.896875,0.015348
489,50,25,balanced,gini,0.896872,0.015375
523,50,33,None,gini,0.896869,0.015558
674,100,22,None,entropy,0.896142,0.012411
520,50,33,balanced,entropy,0.896137,0.016129
678,100,23,None,entropy,0.896137,0.014878
476,50,22,balanced,entropy,0.896137,0.014504
679,100,23,None,gini,0.896137,0.012248
709,100,31,balanced,gini,0.896134,0.016656
706,100,30,None,entropy,0.896134,0.016808
665,100,20,balanced,gini,0.896134,0.013144
722,100,34,None,entropy,0.896131,0.017938
690,100,26,None,entropy,0.896131,0.016504
667,100,20,None,gini,0.896131,0.014156
474,50,21,None,entropy,0.896131,0.016350
464,50,19,balanced,entropy,0.896131,0.017486
670,100,21,None,entropy,0.896128,0.018128
676,100,23,balanced,entropy,0.896128,0.014949
461,50,18,balanced,gini,0.896126,0.017667
477,50,22,balanced,gini,0.896123,0.020695
473,50,21,balanced,gini,0.896120,0.017708
532,50,36,balanced,entropy,0.895396,0.016853
524,50,34,balanced,entropy,0.895396,0.016853
490,50,25,None,entropy,0.895396,0.017189
725,100,35,balanced,gini,0.895393,0.016550
721,100,34,balanced,gini,0.895393,0.016550
729,100,36,balanced,gini,0.895393,0.016550
506,50,29,None,entropy,0.895390,0.018444
510,50,30,None,entropy,0.895390,0.020444
528,50,35,balanced,entropy,0.894655,0.016716
560,50,43,balanced,entropy,0.894655,0.016716
536,50,37,balanced,entropy,0.894655,0.016716
564,50,44,balanced,entropy,0.894655,0.016716
544,50,39,balanced,entropy,0.894655,0.016716
504,50,29,balanced,entropy,0.894655,0.014614
548,50,40,balanced,entropy,0.894655,0.016716
552,50,41,balanced,entropy,0.894655,0.016716
584,50,49,balanced,entropy,0.894655,0.016716
580,50,48,balanced,entropy,0.894655,0.016716
576,50,47,balanced,entropy,0.894655,0.016716
556,50,42,balanced,entropy,0.894655,0.016716
572,50,46,balanced,entropy,0.894655,0.016716
568,50,45,balanced,entropy,0.894655,0.016716
540,50,38,balanced,entropy,0.894655,0.016716
512,50,31,balanced,entropy,0.894652,0.016229
769,100,46,balanced,gini,0.894652,0.015726
773,100,47,balanced,gini,0.894652,0.015726
733,100,37,balanced,gini,0.894652,0.015726
761,100,44,balanced,gini,0.894652,0.015726
781,100,49,balanced,gini,0.894652,0.015726
753,100,42,balanced,gini,0.894652,0.015726
749,100,41,balanced,gini,0.894652,0.015726
745,100,40,balanced,gini,0.894652,0.015726
741,100,39,balanced,gini,0.894652,0.015726
777,100,48,balanced,gini,0.894652,0.015726
737,100,38,balanced,gini,0.894652,0.015726
757,100,43,balanced,gini,0.894652,0.015726
765,100,45,balanced,gini,0.894652,0.015726
486,50,24,None,entropy,0.894650,0.013875
661,100,19,balanced,gini,0.894650,0.015375
677,100,23,balanced,gini,0.894650,0.014265
460,50,18,balanced,entropy,0.894650,0.012848
494,50,26,None,entropy,0.894647,0.017733
483,50,23,None,gini,0.894647,0.011012
469,50,20,balanced,gini,0.894647,0.015767
663,100,19,None,gini,0.894644,0.017276
475,50,21,None,gini,0.894641,0.018675
470,50,20,None,entropy,0.894636,0.017954
516,50,32,balanced,entropy,0.893912,0.014431
682,100,24,None,entropy,0.893909,0.015172
694,100,27,None,entropy,0.893906,0.016429
671,100,21,None,gini,0.893906,0.013483
485,50,24,balanced,gini,0.893901,0.021431
500,50,28,balanced,entropy,0.893901,0.020623
290,10,24,None,entropy,0.893171,0.014750
487,50,24,None,gini,0.893171,0.012746
317,10,31,balanced,gini,0.893168,0.022328
479,50,22,None,gini,0.893165,0.015350
508,50,30,balanced,entropy,0.893165,0.016719
488,50,25,balanced,entropy,0.893165,0.015890
657,100,18,balanced,gini,0.893163,0.016246
644,100,15,balanced,entropy,0.893157,0.015412
472,50,21,balanced,entropy,0.892427,0.015435
496,50,27,balanced,entropy,0.892425,0.016157
502,50,28,None,entropy,0.892422,0.019561
659,100,18,None,gini,0.892416,0.015501
653,100,17,balanced,gini,0.891687,0.012318
655,100,17,None,gini,0.891684,0.008987
280,10,22,balanced,entropy,0.891678,0.024801
658,100,18,None,entropy,0.891673,0.017597
480,50,23,balanced,entropy,0.891670,0.019118
288,10,24,balanced,entropy,0.890946,0.014964
313,10,30,balanced,gini,0.890946,0.023649
492,50,26,balanced,entropy,0.890940,0.016087
452,50,16,balanced,entropy,0.890940,0.017854
297,10,26,balanced,gini,0.890940,0.011954
471,50,20,None,gini,0.890938,0.011016
298,10,26,None,entropy,0.890932,0.023139
333,10,35,balanced,gini,0.890200,0.022492
353,10,40,balanced,gini,0.890200,0.022492
389,10,49,balanced,gini,0.890200,0.022492
385,10,48,balanced,gini,0.890200,0.022492
361,10,42,balanced,gini,0.890200,0.022492
377,10,46,balanced,gini,0.890200,0.022492
381,10,47,balanced,gini,0.890200,0.022492
369,10,44,balanced,gini,0.890200,0.022492
349,10,39,balanced,gini,0.890200,0.022492
345,10,38,balanced,gini,0.890200,0.022492
325,10,33,balanced,gini,0.890200,0.022492
373,10,45,balanced,gini,0.890200,0.022492
329,10,34,balanced,gini,0.890200,0.022492
341,10,37,balanced,gini,0.890200,0.022492
337,10,36,balanced,gini,0.890200,0.022492
365,10,43,balanced,gini,0.890200,0.022492
357,10,41,balanced,gini,0.890200,0.022492
456,50,17,balanced,entropy,0.890194,0.015247
448,50,15,balanced,entropy,0.890194,0.012001
465,50,19,balanced,gini,0.889459,0.012990
467,50,19,None,gini,0.889448,0.019361
305,10,28,balanced,gini,0.888724,0.016443
309,10,29,balanced,gini,0.888718,0.025831
321,10,32,balanced,gini,0.888718,0.021533
457,50,17,balanced,gini,0.888715,0.012702
645,100,15,balanced,gini,0.888713,0.014917
462,50,18,None,entropy,0.888710,0.018100
650,100,16,None,entropy,0.888707,0.016706
275,10,20,None,gini,0.887983,0.015258
662,100,19,None,entropy,0.887972,0.019613
453,50,16,balanced,gini,0.887972,0.018725
459,50,17,None,gini,0.887972,0.012360
649,100,16,balanced,gini,0.887964,0.013708
302,10,27,None,entropy,0.887239,0.021589
303,10,27,None,gini,0.887239,0.016517
306,10,28,None,entropy,0.887237,0.019448
264,10,18,balanced,entropy,0.887231,0.021871
454,50,16,None,entropy,0.887231,0.020049
292,10,25,balanced,entropy,0.887228,0.021367
307,10,28,None,gini,0.887228,0.016442
654,100,17,None,entropy,0.887223,0.018386
310,10,29,None,entropy,0.886499,0.017644
285,10,23,balanced,gini,0.886490,0.020821
318,10,31,None,entropy,0.886488,0.021497
117,5,30,balanced,gini,0.886485,0.030692
334,10,35,None,entropy,0.885752,0.018690
274,10,20,None,entropy,0.885752,0.007265
322,10,32,None,entropy,0.885750,0.019712
364,10,43,balanced,entropy,0.885747,0.019586
376,10,46,balanced,entropy,0.885747,0.019586
356,10,41,balanced,entropy,0.885747,0.019586
332,10,35,balanced,entropy,0.885747,0.019586
368,10,44,balanced,entropy,0.885747,0.019586
352,10,40,balanced,entropy,0.885747,0.019586
336,10,36,balanced,entropy,0.885747,0.019586
360,10,42,balanced,entropy,0.885747,0.019586
344,10,38,balanced,entropy,0.885747,0.019586
388,10,49,balanced,entropy,0.885747,0.019586
340,10,37,balanced,entropy,0.885747,0.019586
380,10,47,balanced,entropy,0.885747,0.019586
348,10,39,balanced,entropy,0.885747,0.019586
384,10,48,balanced,entropy,0.885747,0.019586
300,10,27,balanced,entropy,0.885747,0.021953
372,10,45,balanced,entropy,0.885747,0.019586
284,10,23,balanced,entropy,0.885744,0.014624
266,10,18,None,entropy,0.885744,0.020288
278,10,21,None,entropy,0.885739,0.015784
466,50,19,None,entropy,0.885739,0.023271
326,10,33,None,entropy,0.885012,0.018476
301,10,27,balanced,gini,0.885012,0.024739
342,10,37,None,entropy,0.885012,0.018476
338,10,36,None,entropy,0.885012,0.018476
651,100,16,None,gini,0.885006,0.013562
316,10,31,balanced,entropy,0.885006,0.018952
289,10,24,balanced,gini,0.885006,0.022183
293,10,25,balanced,gini,0.885003,0.027825
282,10,22,None,entropy,0.884268,0.013982
640,100,14,balanced,entropy,0.884268,0.012770
320,10,32,balanced,entropy,0.884265,0.018417
324,10,33,balanced,entropy,0.884265,0.018417
458,50,17,None,entropy,0.884263,0.016570
311,10,29,None,gini,0.884257,0.014101
646,100,15,None,entropy,0.884254,0.016957
286,10,23,None,entropy,0.884254,0.024631
82,5,21,None,entropy,0.884246,0.019299
358,10,41,None,entropy,0.883530,0.018403
390,10,49,None,entropy,0.883530,0.018403
362,10,42,None,entropy,0.883530,0.018403
386,10,48,None,entropy,0.883530,0.018403
366,10,43,None,entropy,0.883530,0.018403
374,10,45,None,entropy,0.883530,0.018403
378,10,46,None,entropy,0.883530,0.018403
370,10,44,None,entropy,0.883530,0.018403
382,10,47,None,entropy,0.883530,0.018403
350,10,39,None,entropy,0.883530,0.018403
346,10,38,None,entropy,0.883530,0.018403
354,10,40,None,entropy,0.883530,0.018403
328,10,34,balanced,entropy,0.883525,0.017987
308,10,29,balanced,entropy,0.883525,0.017524
94,5,24,None,entropy,0.883525,0.016391
314,10,30,None,entropy,0.883525,0.019880
315,10,30,None,gini,0.883525,0.020164
312,10,30,balanced,entropy,0.883522,0.019191
138,5,35,None,entropy,0.883522,0.023815
323,10,32,None,gini,0.883522,0.018155
299,10,26,None,gini,0.883519,0.018658
110,5,28,None,entropy,0.883519,0.024293
463,50,18,None,gini,0.883514,0.017771
276,10,21,balanced,entropy,0.883508,0.022326
277,10,21,balanced,gini,0.883508,0.017969
279,10,21,None,gini,0.882787,0.010132
330,10,34,None,entropy,0.882784,0.019734
146,5,37,None,entropy,0.882781,0.023810
142,5,36,None,entropy,0.882781,0.023810
449,50,15,balanced,gini,0.882776,0.020205
319,10,31,None,gini,0.882776,0.015772
304,10,28,balanced,entropy,0.882773,0.019379
268,10,19,balanced,entropy,0.882773,0.020922
281,10,22,balanced,gini,0.882770,0.022205
287,10,23,None,gini,0.882043,0.016002
283,10,22,None,gini,0.882038,0.020707
272,10,20,balanced,entropy,0.882038,0.017552
391,10,49,None,gini,0.882035,0.019749
444,50,14,balanced,entropy,0.882035,0.013676
331,10,34,None,gini,0.882035,0.019749
335,10,35,None,gini,0.882035,0.019749
367,10,43,None,gini,0.882035,0.019749
455,50,16,None,gini,0.882035,0.018919
339,10,36,None,gini,0.882035,0.019749
343,10,37,None,gini,0.882035,0.019749
375,10,45,None,gini,0.882035,0.019749
359,10,41,None,gini,0.882035,0.019749
387,10,48,None,gini,0.882035,0.019749
371,10,44,None,gini,0.882035,0.019749
351,10,39,None,gini,0.882035,0.019749
383,10,47,None,gini,0.882035,0.019749
347,10,38,None,gini,0.882035,0.019749
363,10,42,None,gini,0.882035,0.019749
379,10,46,None,gini,0.882035,0.019749
355,10,40,None,gini,0.882035,0.019749
450,50,15,None,entropy,0.882032,0.017878
130,5,33,None,entropy,0.881300,0.024073
327,10,33,None,gini,0.881294,0.017775
178,5,45,None,entropy,0.880559,0.024340
158,5,40,None,entropy,0.880559,0.024340
154,5,39,None,entropy,0.880559,0.024340
150,5,38,None,entropy,0.880559,0.024340
170,5,43,None,entropy,0.880559,0.024340
174,5,44,None,entropy,0.880559,0.024340
114,5,29,None,entropy,0.880559,0.021970
166,5,42,None,entropy,0.880559,0.024340
194,5,49,None,entropy,0.880559,0.024340
190,5,48,None,entropy,0.880559,0.024340
162,5,41,None,entropy,0.880559,0.024340
182,5,46,None,entropy,0.880559,0.024340
186,5,47,None,entropy,0.880559,0.024340
121,5,31,balanced,gini,0.880559,0.025454
641,100,14,balanced,gini,0.880556,0.015667
647,100,15,None,gini,0.880556,0.019180
642,100,14,None,entropy,0.880542,0.021665
101,5,26,balanced,gini,0.879821,0.017663
122,5,31,None,entropy,0.879813,0.026031
258,10,16,None,entropy,0.879813,0.021001
273,10,20,balanced,gini,0.879810,0.026868
636,100,13,balanced,entropy,0.879810,0.017757
270,10,19,None,entropy,0.879807,0.026192
126,5,32,None,entropy,0.879807,0.028098
632,100,12,balanced,entropy,0.879807,0.020761
294,10,25,None,entropy,0.879086,0.018394
118,5,30,None,entropy,0.879078,0.022354
109,5,28,balanced,gini,0.879075,0.024596
445,50,14,balanced,gini,0.879069,0.017076
296,10,26,balanced,entropy,0.879069,0.018014
93,5,24,balanced,gini,0.879064,0.025450
85,5,22,balanced,gini,0.879064,0.024878
265,10,18,balanced,gini,0.879064,0.018385
436,50,12,balanced,entropy,0.879058,0.020674
189,5,48,balanced,gini,0.878337,0.024109
137,5,35,balanced,gini,0.878337,0.024109
181,5,46,balanced,gini,0.878337,0.024109
193,5,49,balanced,gini,0.878337,0.024109
161,5,41,balanced,gini,0.878337,0.024109
177,5,45,balanced,gini,0.878337,0.024109
141,5,36,balanced,gini,0.878337,0.024109
149,5,38,balanced,gini,0.878337,0.024109
173,5,44,balanced,gini,0.878337,0.024109
169,5,43,balanced,gini,0.878337,0.024109
153,5,39,balanced,gini,0.878337,0.024109
157,5,40,balanced,gini,0.878337,0.024109
165,5,42,balanced,gini,0.878337,0.024109
145,5,37,balanced,gini,0.878337,0.024109
185,5,47,balanced,gini,0.878337,0.024109
125,5,32,balanced,gini,0.878337,0.024109
129,5,33,balanced,gini,0.878337,0.024109
133,5,34,balanced,gini,0.878337,0.024109
134,5,34,None,entropy,0.878334,0.025979
295,10,25,None,gini,0.878329,0.020564
102,5,26,None,entropy,0.878320,0.017107
451,50,15,None,gini,0.878320,0.019371
262,10,17,None,entropy,0.878315,0.021683
637,100,13,balanced,gini,0.877582,0.017657
441,50,13,balanced,gini,0.877582,0.020920
90,5,23,None,entropy,0.876853,0.016515
291,10,24,None,gini,0.876847,0.022341
113,5,29,balanced,gini,0.876842,0.032018
105,5,27,balanced,gini,0.876109,0.026848
70,5,18,None,entropy,0.876106,0.011219
98,5,25,None,entropy,0.876106,0.017060
254,10,15,None,entropy,0.875366,0.018615
442,50,13,None,entropy,0.875360,0.020876
81,5,21,balanced,gini,0.875355,0.016311
271,10,19,None,gini,0.875349,0.024118
440,50,13,balanced,entropy,0.874628,0.015444
107,5,27,None,gini,0.874619,0.011933

**Выводы**: результаты аналогичны разделу 4

## 6. Predictions

1. Choose the best model and use it to make predictions for the test dataset.
2. Calculate the final accuracy.

In [19]:
best_model = grid_search_forest.best_estimator_
y_pred = best_model.predict(X_test)
print(f'Accuracy на тестовой выборке: {accuracy_score(y_test, y_pred)}')

Accuracy на тестовой выборке: 0.9260355029585798